# This is a basic workflow to help you get started with Actions

name: MirrorWorld Staging DI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [mirrorworld/staging]
  pull_request:
    branches: [mirrorworld/staging]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: bahmutov/npm-install@v1
        with:
          useLockFile: false
      - run: npm run build-staging
      - run: npm run publish-cdn
      - name: rsync deployments
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -av --exclude="node_modules"
          remote_path: ~/mirror-nfts-web-staging
          remote_host: 13.57.6.234
          remote_user: ubuntu
          remote_key: ${{ secrets.DEPLOY_KEY }}
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: 13.57.6.234
          username: ubuntu
          key: ${{ secrets.DEPLOY_KEY }}
          port: ${{ secrets.PORT }}
          script: cd ~/mirror-nfts-web-staging && npm i && pm2 restart ecosystem.config.js --only mirror-nfts-web-staging
